import { z } from 'zod'
import { NotFoundError } from '../../shared/middleware/error.middleware.js'
import { anthropic, CLAUDE_MODEL } from '../../shared/ai/anthropic.client.js'
import { launchBrowser, closeBrowser } from '../../shared/browser/playwright.client.js'
import type { DocPage, DocPageTreeNode, CreatePageInput, UpdatePageInput, ReorderItem } from './page.types.js'
import * as pageRepo from './page.repository.js'

export interface AutoGenerateDeps {
  findProjectById: (id: string) => Promise<{
    baseUrl: string
    name: string
    context: string | null
  } | null>
}

export async function createPage(input: CreatePageInput): Promise<DocPage> {
  return pageRepo.createPage(input)
}

export async function getPage(id: string): Promise<DocPage> {
  const page = await pageRepo.findPageById(id)
  if (!page) throw new NotFoundError('Page')
  return page
}

export async function getPageTree(projectId: string): Promise<DocPageTreeNode[]> {
  const pages = await pageRepo.findPagesByProjectId(projectId)
  return pageRepo.buildTree(pages)
}

export async function getPageSiblings(projectId: string, excludePageId?: string): Promise<DocPage[]> {
  const pages = await pageRepo.findPagesByProjectId(projectId)
  return excludePageId ? pages.filter((p) => p.id !== excludePageId) : pages
}

export async function updatePage(id: string, input: UpdatePageInput): Promise<DocPage> {
  const page = await pageRepo.findPageById(id)
  if (!page) throw new NotFoundError('Page')
  return pageRepo.updatePage(id, input)
}

export async function deletePage(id: string): Promise<void> {
  const page = await pageRepo.findPageById(id)
  if (!page) throw new NotFoundError('Page')
  return pageRepo.deletePage(id)
}

export async function reorderPages(items: ReorderItem[]): Promise<void> {
  return pageRepo.reorderPages(items)
}

// --- Autonomous structure generation ---

const PageProposalSchema = z.object({
  pages: z.array(z.object({
    title: z.string(),
    slug: z.string(),
    startUrl: z.string(),
    goal: z.string(),
    parentSlug: z.string().nullable(),
    sortOrder: z.number(),
  })),
})

export async function autoGenerateStructure(projectId: string): Promise<DocPage[]> {
  // Import project repo inline to avoid cross-feature import at module level
  const { findProjectById } = await import('../project/project.repository.js')

  const project = await findProjectById(projectId)
  if (!project) throw new NotFoundError('Project')

  // Launch browser to scan the site
  const session = await launchBrowser()

  try {
    const page = session.context.activePage()
    if (!page) throw new Error('No active page')

    await page.goto(project.baseUrl, { waitUntil: 'networkidle' })

    // Extract the site structure using Stagehand
    const pageText = await session.extract()

    // Ask Claude to propose a documentation structure
    const response = await anthropic.messages.create({
      model: CLAUDE_MODEL,
      max_tokens: 4096,
      messages: [{
        role: 'user',
        content: `You are a documentation architect. Analyze this website and propose a documentation structure.

## Website
Name: ${project.name}
URL: ${project.baseUrl}
${project.context ? `Context: ${project.context}` : ''}

## Page Content
${pageText.pageText.slice(0, 5000)}

## Task
Propose a documentation structure with 5-15 pages organized in a hierarchy. Each page should document a specific feature or section of the site.

Think about:
- What are the main sections/features of this site?
- What would a new user need to learn?
- What's the logical order of documentation?
- Which pages are top-level and which are sub-pages?

Respond with a JSON object:
{
  "pages": [
    {
      "title": "Getting Started",
      "slug": "getting-started",
      "startUrl": "https://example.com",
      "goal": "Document the homepage and first-time user experience",
      "parentSlug": null,
      "sortOrder": 0
    },
    {
      "title": "Navigation",
      "slug": "navigation",
      "startUrl": "https://example.com",
      "goal": "Document the main navigation and site structure",
      "parentSlug": "getting-started",
      "sortOrder": 1
    }
  ]
}

Rules:
- startUrl should be the most relevant URL for that page (use the base URL if unsure)
- parentSlug should reference another page's slug for nesting, or null for top-level
- slug must be lowercase with hyphens only
- goal should be specific enough for an AI agent to explore and document
- sortOrder determines display order among siblings

Respond ONLY with the JSON object.`,
      }],
    })

    const textBlock = response.content.find((b) => b.type === 'text')
    if (!textBlock || textBlock.type !== 'text') throw new Error('No response from Claude')

    // Parse the JSON — handle markdown code fences
    let jsonStr = textBlock.text.trim()
    if (jsonStr.startsWith('```')) {
      jsonStr = jsonStr.replace(/^```(?:json)?\n?/, '').replace(/\n?```$/, '')
    }

    const parsed = JSON.parse(jsonStr) as unknown
    const { pages: proposals } = PageProposalSchema.parse(parsed)

    // Create pages in DB — first pass: create all pages
    const slugToId = new Map<string, string>()
    const createdPages: DocPage[] = []

    // First create top-level pages (parentSlug === null)
    for (const p of proposals.filter((p) => !p.parentSlug)) {
      const created = await pageRepo.createPage({
        projectId,
        title: p.title,
        slug: p.slug,
        startUrl: p.startUrl,
        goal: p.goal,
        sortOrder: p.sortOrder,
      })
      slugToId.set(p.slug, created.id)
      createdPages.push(created)
    }

    // Then create child pages
    for (const p of proposals.filter((p) => p.parentSlug)) {
      const parentId = slugToId.get(p.parentSlug!) ?? undefined
      const created = await pageRepo.createPage({
        projectId,
        parentId,
        title: p.title,
        slug: p.slug,
        startUrl: p.startUrl,
        goal: p.goal,
        sortOrder: p.sortOrder,
      })
      slugToId.set(p.slug, created.id)
      createdPages.push(created)
    }

    return createdPages
  } finally {
    await closeBrowser(session)
  }
}
